/* export const homeObjOne ={
    id: 'gallery',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'This is the top line',
    headline: 'This is the headline',
    description: 'Here we will write the description',
    buttonLabel: 'Button',
    imgStart: false,
    img: require('../../images/nFlag.png').default,
    alt: 'image',
    dark: true,
    primary: true,
    darkText: true,
};
 */
export const homeObjTwo = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "This is the top line",
  headline: "This is the headline",
  description: "Here we will write the description",
  buttonLabel: "Button",
  imgStart: true,
  img: require("../../images/nFlag.png").default,
  alt: "image",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjThree = {
  id: "engage",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "This is the top line",
  headline: "This is the headline",
  description: "Here we will write the description",
  buttonLabel: "Button",
  imgStart: false,
  img: require("../../images/nFlag.png").default,
  alt: "image",
  dark: true,
  primary: true,
  darkText: true,
};
